server:
  port: 8110
spring:
  data:
    mongodb:
      username: root
      password: Admin@123
      host: localhost
      port: 27017
      database: message
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # properties:
      #   spring.json.type.mapping: orderConfirmation:com.microservices.ecommerce.kafka.OrderConfirmation

application:
  config:
    user-url: http://gateway-service:8222/api/v1/users
