spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: appointment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/appointment
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
    user: root
    password: Admin@123
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: appointmentNotification:com.microservices.appointment.appointment.AppointmentResponse

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
