services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - pj-03-psychological-healthcare-be_microservices-net

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery
    ports:
      - "8761:8761"
    networks:
      - pj-03-psychological-healthcare-be_microservices-net
    depends_on:
      - config-server

networks:
  pj-03-psychological-healthcare-be_microservices-net:
    external: true
