server:
  port: 8000
spring:
  mail:
    host: mail-dev
    port: 1025
    username: root
    password: Admin@123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
