spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: media-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB